### PR TITLE
Ingress Hostname and Path collision at Tenant level

### LINKED ISSUE #358: Ingress hostname collision check at Tenant level
# Problem statement
Going to think about how to refactor the ingress hostname collision checks in Capsule since it looks there is still a grey area there

- https://github.com/clastix/capsule/issues/218#issuecomment-791940109
- https://github.com/clastix/capsule/issues/218#issuecomment-791942131
- https://github.com/clastix/capsule/issues/218#issuecomment-869014916

Capsule in `v1beta1` implements two different kinds of check for hostname collision  

```yaml
  allowTenantIngressHostnamesCollision: false # default
  allowIngressHostnameCollision: false # default
```

## Option `allowTenantIngressHostnamesCollision`
This implement is a check on the Tenant custom resource creation about the allowed list of `tenant.spec.ingressHostnames.allowed` preventing the cluster admin to create two tenants using the same allowed hostname list:

```yaml
kubectl apply -f - <<EOF
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: gold
spec:
  owners:
  - kind: User
    name: alice
  ingressHostnames:
    allowed:
    - app.clastix.io
---
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: silver
spec:
  owners:
  - kind: User
    name: alice
  ingressHostnames:
    allowed:
    - app.clastix.io
EOF

tenant.capsule.clastix.io/gold created

Error from server (the allowed hostname app.clastix.io is already used by the Tenant gold, cannot proceed): error when creating "STDIN": admission webhook "tenants.capsule.clastix.io" denied the request: the allowed hostname app.clastix.io is already used by the Tenant gold, cannot proceed
```

Only the first tenant is created. However, the `allowTenantIngressHostnamesCollision` check does not apply to regex

```yaml
kubectl apply -f - <<EOF
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: gold
spec:
  owners:
  - kind: User
    name: alice
  ingressHostnames:
    allowedRegex: ".clastix.io$"
---
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: silver
spec:
  owners:
  - kind: User
    name: alice
  ingressHostnames:
    allowedRegex: ".clastix.io$"
EOF

tenant.capsule.clastix.io/gold created
tenant.capsule.clastix.io/silver created
```

Both the `gold` and `silver` tenants above can now use the same domain `clastix.io`.

## Option `allowIngressHostnameCollision`
As tenant admin, let's to create a couple of namespaces in each tenant:

```
kubectl --as alice --as-group capsule.clastix.io create ns gold-production
kubectl --as alice --as-group capsule.clastix.io create ns gold-development
kubectl --as alice --as-group capsule.clastix.io create ns silver-production
kubectl --as alice --as-group capsule.clastix.io create ns silver-development
```

Working on both the tenants

```yaml
kubectl --as alice --as-group capsule.clastix.io apply -f - <<EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: gold-production
spec:
  rules:
    - host: webapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: silver-production
spec:
  rules:
    - host: webapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 80
EOF
ingress.networking.k8s.io/example created
Error from server (hostname webapp.clastix.io is already used across the cluster: please, reach out to the system administrators): error when creating "STDIN": admission webhook "ingress.capsule.clastix.io" denied the request: hostname webapp.clastix.io is already used across the cluster: please, reach out to the system administrators
```

Good job! Capsule prevents the same `webapp.clastix.io` hostname across namespaces because of the `allowIngressHostnameCollision=false`.

> Please note the other option `allowTenantIngressHostnamesCollision=false` does not play here.

Working on the `gold-production` tenant only

```yaml
kubectl --as alice --as-group capsule.clastix.io delete ing --all -n gold-production
kubectl --as alice --as-group capsule.clastix.io apply -f - <<EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: gold-production
spec:
  rules:
    - host: goldapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: goldapp
              servicePort: 80
    - host: goldapp.clastix.io
      http:
        paths:
          - path: /testpath
            backend:
              serviceName: test
              servicePort: 80
EOF
ingress.networking.k8s.io/example created
```

However, if we have to cordon the `https://goldapp.clastix.io/testpath` from public access

```yaml
kubectl --as alice --as-group capsule.clastix.io delete ing example -n gold-production
kubectl --as alice --as-group capsule.clastix.io apply -f - <<EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: gold-production
spec:
  rules:
    - host: goldapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: goldapp
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testpath
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
  namespace: gold-production
spec:
  rules:
    - host: goldapp.clastix.io
      http:
        paths:
          - path: /testpath
            backend:
              serviceName: test
              servicePort: 80
EOF
ingress.networking.k8s.io/example created
Error from server (hostname goldapp.clastix.io is already used across the cluster: please, reach out to the system administrators): error when creating "STDIN": admission webhook "ingress.capsule.clastix.io" denied the request: hostname goldapp.clastix.io is already used across the cluster: please, reach out to the system administrators

```

The second ingress is denied because of the same `goldapp.clastix.io` across namespaces and `allowIngressHostnameCollision=false`. This is very common as pointed out by @MaxFedotov.

As cluster admin, let's to allow hostname collision by putting `allowIngressHostnameCollision=true` in Capsule configuration.

As tenant admin, now it's possible to create two ingresses in the same namespace with the same hostname `goldapp.clastix.io` but different paths

```
kubectl --as alice --as-group capsule.clastix.io apply -f - <<EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: gold-production
spec:
  rules:
    - host: goldapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: goldapp
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testpath
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16
  namespace: gold-production
spec:
  rules:
    - host: goldapp.clastix.io
      http:
        paths:
          - path: /testpath
            backend:
              serviceName: test
              servicePort: 80
EOF
ingress.networking.k8s.io/example created
ingress.networking.k8s.io/testpath created
```

Now there are no checks to prevent tenant owner to:

- create two ingresses with same hostname in two different namespaces of the same tenant
- create two ingresses with same hostname in two different namespaces of two different tenants

```yaml
kubectl --as alice --as-group capsule.clastix.io apply -f - <<EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: gold-production
spec:
  rules:
    - host: webapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testpath
  namespace: gold-development
spec:
  rules:
    - host: webapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testpath
  namespace: silver-production
spec:
  rules:
    - host: webapp.clastix.io
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp
              servicePort: 80
EOF

ingress.networking.k8s.io/example created
ingress.networking.k8s.io/testpath created
ingress.networking.k8s.io/testpath created
```

# Proposal
Long story here to say we have to address three common scenarios, from high to low priority

1. prevent hostname collision across tenants - high
2. prevent hostname collision across namespaces of the same tenant - medium
3. prevent hostname collision across same namespace - low

_Unfortunately, the current implementation of `allowTenantIngressHostnamesCollision` does not help here and, in general, it has a limited utility (imho)._

- Change the behaviour of `allowTenantIngressHostnamesCollision` to prevent hostname collision across tenants at runtime (first scenario)
- Change the behaviour of `allowIngressHostnameCollision` to prevent hostname collision across namespaces of the same tenant (second scenario)
- Do not address the third scenario since it's more under control and responsibility of the developer than the cluster admin

@prometherion @MaxFedotov please, comment.

### PR DESCRIPTION
**Pull request by prometherion**
Closes #358.

On `CapsuleConfiguration` API side, the collision flags have been removed since this is going to be managed at Tenant level, also for the Tenant allowed hostnames.

Now the collision check is taking care also of the path, allowing creating several Ingress but with different path since it's a quite common pattern due to some limitations of specific Ingress Controller.

Last but not least, on `v1beta` a new `IngressOptions` struct has been implemented, grouping allowed IngressClass, allowed hostnames, and the new scope feature (backported to `v1alpha1` too with the annotation `ingress.capsule.clastix.io/hostname-collision-scope` accepting one of the enum values `Cluster`, `Tenant`, `Namespace`, `Disabled`, this latter one the default).

### CODE REVIEW

**Comment by prometherion** [comment]
Thanks @MaxFedotov, I totally forgot it: should be easy to achieve, BTW.

Going to open an issue on proxy side referencing your comment.

**Review by MaxFedotov — COMMENTED** [review]
lgtm!

**Review by bsctl — COMMENTED** [review]
@prometherion 
noted that when collision is detected, the error message does not return the colliding ingress, `"STDIN"` is reported instead.

`Error from server (hostname web.uno.fastcloud.it is already used across the cluster: please, reach out to the system administrators): error when creating "STDIN": admission webhook "ingress.capsule.clastix.io" denied the request: hostname web.uno.fastcloud.it is already used across the cluster: please, reach out to the system administrators`

Also the collision events are not recorded in `kubectl describe tnt <tenant>`

**Comment by prometherion** [comment]
We had a bug in the Event recording, fixed with last commit.

**Comment by bsctl** [comment]
Events are now emitted and collected

```
Events:
  Type     Reason                    Age                From               Message
  ----     ------                    ----               ----               -------
  Normal   NamespaceCreationWebhook  12m                tenant-webhook     Namespace due-production has been assigned to the desired Tenant
  Normal   due-production            11m (x4 over 12m)  tenant-controller  Ensuring Namespace metadata
  Normal   due-production            11m (x4 over 12m)  tenant-controller  Ensuring Capsule RoleBinding namespace:admin
  Normal   due-production            11m (x4 over 12m)  tenant-controller  Ensuring Capsule RoleBinding namespace-deleter
  Normal   NamespaceCreationWebhook  11m                tenant-webhook     Namespace due-development has been assigned to the desired Tenant
  Normal   due-development           11m (x2 over 11m)  tenant-controller  Ensuring Namespace metadata
  Normal   due-development           11m (x2 over 11m)  tenant-controller  Ensuring Capsule RoleBinding namespace:admin
  Normal   due-development           11m (x2 over 11m)  tenant-controller  Ensuring Capsule RoleBinding namespace-deleter
  Warning  IngressHostnameCollision  10m                tenant-webhook     Ingress due-production/example hostname is colliding
```

**Comment by bsctl** [comment]
Unfortunately, still see the Ingress referenced as `STDIN` in the error message:

`Error from server (hostname web.fastcloud.it is already used across the cluster: please, reach out to the system administrators): error when creating "STDIN": admission webhook "ingress.capsule.clastix.io" denied the request: hostname web.fastcloud.it is already used across the cluster: please, reach out to the system administrators`

**Comment by prometherion** [comment]
The `STDIN` Is the Input for kubectl when posting the payload, it's something unrelated to Capsule.

**Review by bsctl — APPROVED** [review]
@prometherion LGTM, great work!

**Pull request merged**
