### PR TITLE
Setup Gridsome for the website

### LINKED ISSUE #397: Add a documentation website
# Describe the feature
We should add support for a documentation website, e.g. https://capsule.clastix.io

### PR DESCRIPTION
**Pull request by 93lucasp**
Closes #397 

Setup of the tool used to generate the website documentation

### CODE REVIEW

**Comment by 93lucasp** [comment]
Some Info:

- I changed the folder for the files `MD`, now they are inside a folder called `content` (looking around this should be a correct approach)

- Inside the `MD` files I changed the links that pointed directly to the `MD` files, in some cases by linking to the website page and in some cases directly to the file link on Github.

- I noticed that a `docs/operator/use-cases/node-labels-and-annotations.md` file was added but it was not added in the `docs/operator/use-cases/overview.md` file is it correct or it was a distraction? In this case, it should also be added to the sidebar via the configuration file.

- I also noticed that there is a wrong link [on this page](https://github.com/clastix/capsule/blob/master/docs/operator/overview.md) (the last link) so for now I have commented on it. The correct link perhaps had to be [this](https://github.com/clastix/capsule/blob/master/docs/contributing.md)?

- I have a block of code which was `'''sh` in ---> `'''shell`

After all these changes, I invite you to carefully browse the site https://capsule.clastix.io/ and check that everything is fine.

**Comment by prometherion** [comment]
Thanks @93lucasp, I just fixed the issue you reported and amended the commits since we're following the semantic commit messages.

@bsctl I added some changes to the documentation, please, take a review of it and if it's ok, let's merge it! 🚀

**Review by bsctl — APPROVED** [review]
lgtm +1 to merge
Thanks @93lucasp

**Comment by 93lucasp** [comment]
@prometherion @bsctl when you will merge it, remember also to change the branch on Netlify ;)

**Pull request merged**
