### PR TITLE
Add Amazon EKS documentation

### LINKED ISSUE #302: Is Amazon EKS supported by capsule
# Describe the feature

I would like to know if Amazon EKS is supported by capsule.

I tried to configure capsule in Amazon EKS with users created according the following steps, but it doesn't work.

https://www.eksworkshop.com/beginner/091_iam-groups/intro/

I would like to know if Amazon EKS is supported with "their way" of authentication...

### PR DESCRIPTION
**Pull request by ruzickap**
Fix #302

### CODE REVIEW

**Comment by prometherion** [comment]
First of all, thanks for your first contribution @ruzickap: absolutely appreciated and glad to see Capsule working also on EKS! 🙌🏻 

@bsctl i was thinking we could create a new section (aka a new folder like `use_cases` named `managed_kubernetes` or `cloud_installations`) in the docs regarding installation on managed Kubernetes services: WDYT?

**Comment by ruzickap** [comment]
I put it to `docs/operator/managed-kubernetes` - let me know if it is a good place (or if you prefer different directory).

**Review by bsctl — CHANGES_REQUESTED** [review]
@ruzickap Awesome! Just use `alice` instead of `user1` to have this section consistent with other doc sections. Thanks!

**Comment by ruzickap** [comment]
Fixed...

**Review by bsctl — COMMENTED** [review]
LGTM

**Review by prometherion — APPROVED** [review]

**Pull request merged**
