### PR TITLE
fix: resource quota annotations key max length support

### LINKED ISSUE #772: Resource quota annotations for storage class limits may be too long
# Bug description

When using resource quotas tenant functionality to manage storage class request limits, annotation generated by Capsule very often exceeds the 63 characters length in the name part of the annotation.

# How to reproduce

Create a tenant with request quotas like:

```yaml
resourceQuotas:
  items:
    - hard:
        some-storage-class-name.storageclass.storage.k8s.io/requests.storage: 10Gi
```

Capsule will internally attempt to manage its own annotations on a resource quota, two most prominent:

- `quota.capsule.clastix.io/hard-some-storage-class-name.storageclass.storage.k8s.io.requests.storage`
- `quota.capsule.clastix.io/used-some-storage-class-name.storageclass.storage.k8s.io.requests.storage`

Both take a valid annotation of a kubernetes resource quota and convert it into an invalid Capsule annotation on a Capsule-managed resource quota.

# Expected behavior

Feature should not break silently or the limitation must be clearly documented.

# Logs

```
log:{"level":"error","ts":"2023-06-12T08:26:30.352Z","logger":"controllers.Tenant","msg":"Cannot sync ResourceQuota items","Request.Name":"some-request-name","error":"update of outer ResourceQuota items has failed: ResourceQuota "capsule-resource-quota-name" is invalid: [metadata.annotations: Invalid value: "quota.capsule.clastix.io/used-some-storage-class-name.storageclass.storage.k8s.io_requests.storage": name part must be no more than 63 characters, metadata.annotations: Invalid value: "quota.capsule.clastix.io/hard-some-storage-class-name.storageclass.storage.k8s.io_requests.storage": name part must be no more than 63 characters]"}
```

# Additional context

Irrelevant.

### PR DESCRIPTION
**Pull request by prometherion**
Closes #772.

### CODE REVIEW

**Comment by prometherion** [comment]
Asking for your feedback on this, @radekg, since the bug reporter.

As you can see from the code, we're checking if the resource quota key is exceeding the maximum length of 63 characters, and giving the following precedence:

- plain name
- Capsule annotation with the hashed value
- fully hashed value
- ignoring it, otherwise, it would block Capsule reconciliation.

Please, let me know your thoughts.

**Comment by radekg** [comment]
Let me see what I can do about it. Will try testing this and give feedback based on that. I do need a couple of days. Thank you, @prometherion.

**Comment by prometherion** [comment]
@radekg may I ask you a ping about this, please?

**Comment by prometherion** [comment]
Merging due to inactivity, taking over ownership of the feature.

**Pull request merged**
