### PR TITLE
build(helm): add customLabels and customAnnotations params

### LINKED ISSUE #386: support `customLabels` in capsule helm chart
Sometimes users had some custom logic, which relies on labels that should be present on all application parts (deployment, service, rbac, etc). 

In many charts this is done via `customLabels` param in `values` (see https://github.com/kyverno/kyverno/blob/main/charts/kyverno/templates/_helpers.tpl#L40 as an example). 

@prometherion, @bsctl  What do you think about adding this param to `capsule` helm chart?

### PR DESCRIPTION
**Pull request by MaxFedotov**
closes #386

### CODE REVIEW

**Comment by ptx96** [comment]
This PR will probably have conflicts with #384 due to changes inside servicemonitor.yaml ;
we have to decide whether to leave servicemonitors' own values or not.

@prometherion WDYT?

**Comment by prometherion** [comment]
You're right, @ptx96: we have to have separate values for the ServiceMonitor since the Prometheus Operator would require some matching labels, and applying these to non-ServiceMonitor resources would be silly.

@MaxFedotov may I ask you this change?

**Comment by MaxFedotov** [comment]
> You're right, @ptx96: we have to have separate values for the ServiceMonitor since the Prometheus Operator would require some matching labels, and applying these to non-ServiceMonitor resources would be silly.
> 
> @MaxFedotov may I ask you this change?

Sorry, don't understand what I had to do :( rebase on #384?

**Comment by prometherion** [comment]
My bad @MaxFedotov :)

Once #384 is merged, rebase over `master`, a git conflict should arise and must be fixed.

**Comment by MaxFedotov** [comment]
@prometherion  rebased on master

**Review by prometherion — APPROVED** [review]

**Pull request merged**
