### PR TITLE
Short circuit error returns

### PR DESCRIPTION
**Pull request by gernest**
I came across this after  watching the video presentation. This is
just a it pick. I hope to play around with this soon.

```
	if err != nil {
		return err
	}

	return nil
```

Is the same as

```
	return err
```

### CODE REVIEW

**Comment by prometherion** [comment]
Hey, thanks for this: small things are the one making it great :)

I'm going to Troisi CI back once analyzed the error: we got annoying flaky tests and is like to take any evidence to fix them one by one but expect to get this merged!

**Comment by gernest** [comment]
It is hard to get ci right for operators. I am working on https://github.com/TykTechnologies/tyk-operator. And we have been coming up with crazy things to get ci right.

- we have to accept ci to take longer ( do retries with exponential backoff like crary)
- wait for deployments with `kubectl rollout` this might take forever.
- lots of `exec.CMD` hackery to get things right. I'm surprised it is very consistent now.

I know the use case is different from this project but i feel your pain regarding ci pipelines for operators.

even a simple honest test can turn into flaky one  at any moment.

**Comment by prometherion** [comment]
Hey @gernest, I just merged #176 fixing the flaky test you just faced.

Please, can you rebase your local changes over updated `master` and force push changes?

**Comment by gernest** [comment]
@prometherion done

**Review by prometherion — COMMENTED** [review]
LGTM, thanks a lot for this!

**Pull request merged**
