### PR TITLE
Update Broken Links in README.md

### PR DESCRIPTION
**Pull request by abdulhaseeb2**
Update common use cases link in Capsule readme

### CODE REVIEW

**Comment by bsctl** [comment]
@abdulhaseeb2 Thanks for submitting this PR. Looks good to me, just please follow commits guidelines

> **Commits**
> All the Pull Requests must refer to an already open issue: this is the first phase to contribute also for informing maintainers about the issue.
> 
> Commit's first line should not exceed 50 columns.
> 
> 
> A commit description is welcomed to explain more the changes: just ensure to put a blank line and an arbitrary number of maximum 72 characters long lines, at most one blank line between them.
> 
> Please, split changes into several and documented small commits: this will help us to perform a better review. Commits must follow the Conventional Commits Specification, a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of. This convention dovetails with Semantic Versioning, by describing the features, fixes, and breaking changes made in commit messages. See [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/) to learn about Conventional Commits.
> 
> In case of errors or need of changes to previous commits, fix them squashing to make changes atomic.
>

**Comment by abdulhaseeb2** [comment]
> @abdulhaseeb2 Thanks for submitting this PR. Looks good to me, just please follow commits guidelines
> 
> > **Commits**
> > All the Pull Requests must refer to an already open issue: this is the first phase to contribute also for informing maintainers about the issue.
> > Commit's first line should not exceed 50 columns.
> > A commit description is welcomed to explain more the changes: just ensure to put a blank line and an arbitrary number of maximum 72 characters long lines, at most one blank line between them.
> > Please, split changes into several and documented small commits: this will help us to perform a better review. Commits must follow the Conventional Commits Specification, a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of. This convention dovetails with Semantic Versioning, by describing the features, fixes, and breaking changes made in commit messages. See [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/) to learn about Conventional Commits.
> > In case of errors or need of changes to previous commits, fix them squashing to make changes atomic.

Thank you for the reply. Done!

**Comment by prometherion** [comment]
@abdulhaseeb2 please, squash your commits and amend the commit message in something as follows: `fix(docs): updating broken links`

**Comment by abdulhaseeb2** [comment]
Fixed commit format in PR#474

**Pull request closed without merging**
