### PR TITLE
chore(ci): added fossa license check

### LINKED ISSUE #810: Add an automatic license check for packages on which Capsule depends
# Describe the feature

I would like to include a process inside our GitHub CI that allows us to verify capsule dependencies license 

# What would the new user story look like?

1. A user opens a PR
2. Any dependency package present or inserted inside the code is analyzed
3. The scan result is returned

# Expected behavior
At the end of the analysis, I have a report of the licenses used in capsule dependencies and I know if I am complying with open source license

### PR DESCRIPTION
**Pull request by ptx96**
Closes #810

### CODE REVIEW

**Comment by prometherion** [comment]
Honestly, I've no idea why the action is complaining about the missing secret.

image

**Comment by prometherion** [comment]
In the meanwhile @ptx96 may I ask you to amend the commit and adhere to the DCO?

YMMV
```
Signed-off-by: Author Name <authoremail@example.com>
```

**Comment by ptx96** [comment]
> Honestly, I've no idea why the action is complaining about the missing secret.
> 
> image

Did you choose "all public repositories" from the access policy menu when you created the FOSSA_API_KEY secret?

**Comment by prometherion** [comment]
It is, @ptx96.

image

**Pull request merged**
