### PR TITLE
refactor: better name variables in codebase

### PR DESCRIPTION
**Pull request by ludusrusso**
This is a WP PR to solve #164 

I plan to check the codebase file by file to improve variables names.
This is my approach to choose if a variable should be renamed:
I'm trying to understand the variable meaning by reading the code, if I need to search in the code base for that meaning, then I rename the variable.

Started with

- [x] main.go
- [x] pkg/webhook
- [x] pkg/webhook/ingress
- [x] pkg/webhook/namespacequota
- [x] pkg/webhook/ownerreference
- [x] pkg/webhook/registry
- [x] pkg/webhook/services
- [x] pkg/webhook/tenant
- [x] pkg/webhook/tenantprefix
- [x] pkg/webhook/utils

@prometherion let me know if you like it and if you think I should continue.

### CODE REVIEW

**Review by prometherion — APPROVED** [review]

**Comment by prometherion** [comment]
I think it's safe to merge, feel free to remove the `WIP` so I can proceed merging it!

**Comment by ludusrusso** [comment]
Yep, but I'd like to move on more files! If you prefer I can split this in multiple PR.

**Comment by prometherion** [comment]
Let's keep this PR but separating each change to a specific commit.

**Comment by ludusrusso** [comment]
> Let's keep this PR but separating each change to a specific commit.

Yep as usual.

I'll keep this WP ...

**Comment by ludusrusso** [comment]
@prometherion if test passes you can merge for me!

**Pull request merged**
